prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix biosem: <http://rdf.biosemantics.org/emco/v1.5/vocabularies/>

SELECT distinct ?concept  {

    ?concept a skos:Concept.

FILTER(STRSTARTS(STR(?concept), "http://rdf.biosemantics.org/emco/v1.5/concepts/"))

}