# Concept profile generation and analysis for Gene-Disease paper
# Copyright (C) 2015 Biosemantics Group, Leiden University Medical Center
#  Leiden, The Netherlands
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

"
@author Eelke van der horst
@author Mark thompson
@author Rajaram Kaliyaperumal

@version 0.1
@since 19-09-2014

<p>
  This rscript generate plots fig.2a and fig.2b
</p>

Input Required : geneStats/diseasesStats/overlapsStats file 
  See : Required input files are generated by 'ConceptProfileStats.java' 

Output : plots

" 
library(lattice)
library(latticeExtra)

# Read csv file
mydf <- read.csv('/home/rajaram/work/gene-disease/r-script/dataset/src/diseasesStats', 
                 colClasses=c("integer", "integer", "integer"), header= T, fileEncoding= "windows-1252")

# Get data from 'noOfPMids' column
abstracts <- log(mydf$noOfPMids)
# Get data from 'conceptProfileLength' column
cpLength <- log(mydf$conceptProfileLength)

# Plot parameters
xLabel <- c("log(no.of abstracts)")
yLabel <- c("log(concept profile length)")
title <- c ("Fig 2c (disease)")

xyplot(cpLength ~ abstracts, grid = TRUE, 
       type = c("p", "smooth"), col.line = "red", 
       col="black", pch="*", lwd = 3, main = title, xlab=xLabel, ylab=yLabel)
