# Concept profile generation and analysis for Gene-Disease paper
# Copyright (C) 2015 Biosemantics Group, Leiden University Medical Center
#  Leiden, The Netherlands
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

"
@author Eelke van der horst
@author Mark thompson
@author Rajaram Kaliyaperumal

@version 0.1
@since 03-09-2014

<p>
  This rscript generate plots fig.1d, fig.1e and fig.1f
</p>

Input Required : geneStats/diseasesStats/overlapsStats file 
  See : Required input files are generated by 'ConceptProfileStats.java' 

Output : plots

" 
# Read csv file
mydf <- read.csv('/home/rajaram/work/gene-disease/r-script/dataset/src/genesStats', 
                 colClasses=c("integer", "integer", "integer"), header= T, fileEncoding= "windows-1252")

# Plot parameters
xLimit <- c(0, 10000)
dataSize <- c(500) # histrogram bin size
title <- c("geneConceptProfileStats")
xLabel <- c("concept profile length")
yLabel <- c("density")

# Get data from 'conceptProfileLength' column
conceptProfileLength <- mydf$conceptProfileLength
# Maximum profile length
maxLength <- max(conceptProfileLength)
# Profile median value
median_ <- median(conceptProfileLength)

hist(conceptProfileLength, prob=FALSE, xlim= xLimit,   col="black", 
     breaks=dataSize, main=title, xlab=xLabel, ylab=yLabel)

