# Concept profile generation and analysis for Gene-Disease paper
# Copyright (C) 2015 Biosemantics Group, Leiden University Medical Center
#  Leiden, The Netherlands
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

"
@author Eelke van der horst
@author Mark thompson
@author Rajaram Kaliyaperumal

@version 0.1
@since 18-09-2014

<p>
  This rscript generate plots fig.2c and fig.2d
</p>

Input Required : figure-2d-input-file file 
  See : Required input file is generated by 'https://git.lumc.nl/biosemantics/gene-disease/blob/master/shell-script/script/src/figure-2d-boxplot.sh' 

Output : plots

" 
# Read csv file
mydf <- read.csv('/home/rajaram/work/gene-disease/r-script/dataset/test/figure-2d-sample-data', 
                 colClasses=c("double", "double", "double", "double", "double","double", "double", "double", "double", "double"), header= T, fileEncoding= "windows-1252")
data <- log(mydf)

# Plot parameters
yLabel <- c("log(matchscore)")
title <- c ("Sorted by gene CP length")

#png("/tmp/myplot.png", width=10, height=8, units="in", res=300)
boxplot(data)
title(title, ylab=yLabel)
#dev.off() #only 129kb in size
