# Concept profile generation and analysis for Gene-Disease paper
# Copyright (C) 2015 Biosemantics Group, Leiden University Medical Center
#  Leiden, The Netherlands
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

require 'rdf'
require 'logger'
require 'slop'
require_relative 'converter'


# Convert txt file generated by Concept Profile Matching texting mining method.
#
# Input file format:
#   concept1_id concept2_id match_score pubmed_ids {in CSV}
class CoOccurence_Nanopub_Converter < RDF_File_Converter
  
  
  # Define some useful RDF vocabularies.(Note: Define subclass RDF vocabularies here)   
  
  FOAF = RDF::FOAF
  DC = RDF::DC
  RDFS = RDF::RDFS
  XSD = RDF::XSD
  PROV = RDF::Vocabulary.new('http://www.w3.org/ns/prov#')
  OBO = RDF::Vocabulary.new('http://purl.org/obo/owl/obo#')
  PAV = RDF::Vocabulary.new('http://swan.mindinformatics.org/ontologies/1.2/pav/')   
  SIO = RDF::Vocabulary.new('http://semanticscience.org/resource/')
  STATO = RDF::Vocabulary.new('http://purl.obolibrary.org/obo/')
  PPA = RDF::Vocabulary.new('http://rdf.biosemantics.org/dataset/protein_protein_associations#')
  NP = RDF::Vocabulary.new('http://www.nanopub.org/nschema#')
  $base = RDF::Vocabulary.new($baseURI)

  def initialize
    
    # useful stuff for serializing graph.
    prefixes = {    
    :np => NP,
    :rdf => RDF,
    :sio => SIO,
    :stato => STATO,
    nil => $base
    }

    super(RDF, NP, prefixes)
    # for statistics
    @no_null_genes = 0
    @no_null_diseases = 0
  end

  def convert_header_row(row)
    # do nothing
  end

  def convert_row(row)
    
    
    $coOccResourceURI = "http://rdf.biosemantics.org/dataset/gene_disease_cooccurence"         
    $baseURI = "#{@options[:base_url]}/gene_disease_cooccurence/"
    
    tokens = row.split(",")
    concept1_id = tokens[0]
    concept2_id = tokens[1]
    p_value = nil
    
    if (tokens[2] != 'NaN')      
      p_value = tokens[2].to_f        
    else              
      #puts("row #{@row_index} has no _percentile_value skipped.") 
      return
    end
    
    
    
    if concept2_id == 'null'
      @logger.info("row #{@row_index.to_s} has no disease id. skipped.")
      @no_null_diseases += 1
      return
    end

    if concept1_id == 'null'
      @logger.info("row #{@row_index.to_s} has no gene id. skipped.")
      @no_null_genes += 1
      return
    end    
    
    for i in 3..(tokens.length-1)            
      pubmedID = tokens[i].gsub(/[^0-9]/, "").strip
      
      if pubmedID.length > 0
        @row_index += 1
        create_cooccurence_nanopub(concept1_id, concept2_id, pubmedID)    
      end     
    end  
    
  end


  protected
  def get_options
    options = Slop.parse(:help => true) do
      banner "ruby concept_profile_matching.rb [options]\n"
      on :base_url=, :default => 'http://rdf.biosemantics.org/nanopubs/cpm'
      #on :p_value_cutoff=, 'P-value cutoff, default = 0.05', :default => '0.05'
    end

    super.merge(options)
  end

  protected
  def create_cooccurence_nanopub(gene_id, disease_id, pubmedID)
    
    # setup nanopub
    nanopub = RDF::URI.new("#{$baseURI}#{@row_index.to_s.rjust(6, '0')}")
    assertion = RDF::URI.new("#{$baseURI}#{@row_index.to_s.rjust(6, '0')}#assertion")
    provenance = RDF::URI.new("#{$baseURI}#{@row_index.to_s.rjust(6, '0')}#provenance")
    publication_info = RDF::URI.new("#{$baseURI}#{@row_index.to_s.rjust(6, '0')}#publicationInfo")

    abstract = RDF::URI.new("#{$coOccResourceURI}#abstract_#{@row_index.to_s.rjust(6, '0')}")
    
    # main graph
    create_main_graph(nanopub, assertion, provenance, publication_info)

    # assertion graph    
    save(assertion, [
        # http://edamontology.org/data_2849 = abstract
        [abstract, RDF.type, RDF::URI.new('http://edamontology.org/data_2849')],
        # SIO_000068 = is_part_of
        [RDF::URI.new("http://rdf.biosemantics.org/emco/v1.5/concepts/C#{gene_id}"), SIO['SIO_000068'], abstract],
        [RDF::URI.new("http://rdf.biosemantics.org/emco/v1.5/concepts/C#{disease_id}"), SIO['SIO_000068'], abstract],
        
        [abstract, RDF::URI.new("http://www.bridgmodel.org/owl/3.2#ReferenceToStudyResults.publicationIdentifier"), 
          RDF::URI.new("http://www.ncbi.nlm.nih.gov/pubmed/#{pubmedID}")],
        [abstract, RDF.seeAlso, RDF::URI.new("http://linkedlifedata.com/resource/pubmed/id/#{pubmedID}")]
    ])

    # provenance graph
    create_provenance_graph(provenance, assertion)

    # publication info graph
    create_publication_info_graph(publication_info, nanopub)

    #puts "inserted nanopub <#{nanopub}>"
  end

  private
  def create_provenance_graph(provenance, assertion)
    save(provenance, [
        [assertion, PROV.wasDerivedFrom, RDF::URI.new('http://rdf.biosemantics.org/vocabularies/text_mining#gene_disease_concept_profiles_1980_2014')],
        [assertion, PROV.wasGeneratedBy, RDF::URI.new('http://rdf.biosemantics.org/vocabularies/text_mining#gene_disease_concept_profiles_matching_1980_2014')]
    ])
  end

  private
  def create_publication_info_graph(publication_info, nanopub)
    save(publication_info, [
        [nanopub, DC.rights, RDF::URI.new('http://creativecommons.org/licenses/by/3.0/')],
        [nanopub, DC.rightsHolder, RDF::URI.new('http://biosemantics.org')],
        # B-6035-2012 = Schultes, Erik A
        [nanopub, PAV.authoredBy, RDF::URI.new('http://www.researcherid.com/rid/B-6035-2012')],
        # B-5927-2012 = van Haagen, Herman HHBM
        [nanopub, PAV.authoredBy, RDF::URI.new('http://www.researcherid.com/rid/B-5927-2012')],
        # E-7370-2012 = Mark Thompson
        [nanopub, PAV.createdBy, RDF::URI.new('http://www.researcherid.com/rid/E-7370-2012')],
        # J-7843-2013 = Rajaram Kaliyaperumal
        [nanopub, PAV.createdBy, RDF::URI.new('http://www.researcherid.com/rid/J-7843-2013')],
        # 0000-0002-8777-5612 = Eelke van der horst
        [nanopub, PAV.createdBy, RDF::URI.new('http://orcid.org/0000-0002-8777-5612')],
        [nanopub, DC.created, RDF::Literal.new(Time.now.utc, :datatype => XSD.dateTime)]
    ])
  end
end


# do the work
CoOccurence_Nanopub_Converter.new.convert